export const products = [
  {
    id: "SHEIN001",
    name: "Polka Dot Shirt 101",
    brand: "SHEIN",
    size: "2XL",
    category: "Shirts",
    quantity: 200,
    remainingStock: 199,
    buyingPrice: 100,
    sellingPrice: 200,
    source: "Factory - New",
  },
  {
    id: "SHEIN002",
    name: "Stripe Shirt 102",
    brand: "SHEIN",
    size: "2XL",
    category: "Shirts",
    quantity: 250,
    remainingStock: 249,
    buyingPrice: 120,
    sellingPrice: 220,
    source: "Factory - New",
  },
  {
    id: "UQ0001",
    name: "UQ Pants Crook1",
    brand: "Uniqlo",
    size: "XL",
    category: "Pants",
    quantity: 120,
    remainingStock: 119,
    buyingPrice: 120,
    sellingPrice: 220,
    source: "Resale - Ana Chu",
  },
  {
    id: "UQ0002",
    name: "UQ Skirt Stripe102",
    brand: "Uniqlo",
    size: "XL",
    category: "Skirt",
    quantity: 159,
    remainingStock: 158,
    buyingPrice: 120,
    sellingPrice: 220,
    source: "Resale - Ana Chu",
  },
  {
    id: "F210001",
    name: "Mega Shirt 201",
    brand: "Mudra",
    size: "2XL",
    category: "Shirt",
    quantity: 152,
    remainingStock: 151,
    buyingPrice: 120,
    sellingPrice: 220,
    source: "Factory Overrun",
  },
  {
    id: "F210002",
    name: "Fantasy 302",
    brand: "Mudra",
    size: "2XL",
    category: "Undies",
    quantity: 100,
    remainingStock: 10,
    buyingPrice: 100,
    sellingPrice: 200,
    source: "Factory Overrun",
    isLowStock: true,
  },
];
