export const dashboardData = [
  {
    id: 1,
    label: "Daily Number of Customers",
    value: 40,
    Icon: "/icons/person-walk.png",
    isMain: true,
  },
  {
    id: 2,
    label: "Daily Number of Products Sold",
    value: 40,
    Icon: "/icons/shirt.png",
    isMain: true,
  },
  {
    id: 3,
    label: "Daily Number of Sales",
    value: "Php 20,200.00",
    Icon: "/icons/coins.png",
    isMain: true,
  },
  {
    id: 4,
    label: "Monthly Number of Customers",
    value: 302,
    Icon: "/icons/person-walk.png",
    isMain: false,
  },
  {
    id: 5,
    label: "Monthly Number of Products Sold",
    value: 750,
    Icon: "/icons/shirt.png",
    isMain: false,
  },
  {
    id: 6,
    label: "Monthly Number of Sales",
    value: "Php 120,210.00",
    Icon: "/icons/coins.png",
    isMain: false,
  },
  {
    id: 7,
    label: "Yearly Number of Customers",
    value: 712,
    Icon: "/icons/person-walk.png",
    isMain: false,
  },
  {
    id: 8,
    label: "Yearly Number of Products Sold",
    value: "1,200",
    Icon: "/icons/shirt.png",
    isMain: false,
  },
  {
    id: 9,
    label: "Yearly Number of Sales",
    value: "Php 240,523.50",
    Icon: "/icons/coins.png",
    isMain: false,
  },
];
