export const users = [
  {
    id: 1,
    idNumber: "Not specified",
    name: "Admin User",
    designation: "Admin",
    email: "Admin@gmail.com",
    contact: "09159405211",
    address: "1081 Concepcion Quiapo Manila",
  },
  {
    id: 2,
    idNumber: "Not specified",
    name: "Store Owner",
    designation: "Owner",
    email: "Owner@gmail.com",
    contact: "09172635151",
    address: "2131 Concepcion Quiapo Manila",
  },
  {
    id: 3,
    idNumber: "SALE5001",
    name: "Employee User1",
    designation: "Employee",
    email: "Employee1@gmail.com",
    contact: "09271726165",
    address: "3231 Concepcion Quiapo Manila",
  },
  {
    id: 4,
    idNumber: "SALE5002",
    name: "Employee User2",
    designation: "Employee",
    email: "Employee2@gmail.com",
    contact: "09715625162",
    address: "212 Delcarmen Quiapo Manila",
  },
  {
    id: 5,
    idNumber: "SALE5003",
    name: "Employee User3",
    designation: "Employee",
    email: "Employee3@gmail.com",
    contact: "09262514522",
    address: "213 Mahayhay QC",
  },
  {
    id: 6,
    idNumber: "SHIP004",
    name: "Employee User4",
    designation: "Employee",
    email: "Employee4@gmail.com",
    contact: "09715345162",
    address: "123 Corner Street Tondo Manila",
  },
];